프로그래머, 열정을 말하다. 독후감상문 작성
sirloin-dev/meatplatform pull request #20
Opened 2022-04-11 00:48 UTC by yoonho92

2022-04-11 12:37 UTC, FrancescoJo commented
.idea 는 불필요한 파일들인것 같은데, gitignore 추가해 주시거나 pr 에서 빼 주시는게 좋겠네요

2022-04-11 12:39 UTC, FrancescoJo commented
감상문은 잘 읽었습니다!

2022-04-11 12:39 UTC, FrancescoJo requested changes
`.idea` 제외해주세요

2022-04-12 01:47 UTC, yoonho92 commented
> .idea 는 불필요한 파일들인것 같은데, gitignore 추가해 주시거나 pr 에서 빼 주시는게 좋겠네요

fork된 repository에서 force push로 제거했습니다!

2022-04-12 01:53 UTC, FrancescoJo approved these changes
고생하셨습니다.

LGTM

2022-04-12 02:05 UTC, merged